version: '2.0'

services:
  redis:
    image: redis:latest
    restart: always
    hostname: localhost
    ports:
      - 6379:6379
    volumes:
      - redis/data:/data

  neo4j:
    image: neo4j:latest
    restart: always
    hostname: localhost
    ports:
      - 7474:7474
      -	7373:7373
      -	7687:7687
    volumes:
      - neo4j/data:/data

  mongo:
    image: mongo:latest
    restart: always
    hostname: localhost
    ports:
      - 27017:27017
    volumes:
      - mongo/data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: localhost
    ports:
      - 5672:5672
      - 5671:5671
      - 4369:4369

  sql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: honey678
      MYSQL_DATABASE: UserDB
    volumes:
      - sql/data:/var/lib/mysql
    ports:
      -3306:3306

  api-gateway:
    restart: always
    image: semanticsearch/minerva.api-gateway:1.0.0
    hostname: localhost
    ports:
      - 8000:8000

  eureka-server:
    restart: always
    image: semanticsearch/minerva.eureka-server:1.0.0
    hostname: localhost
    ports:
      - 8070:8070

  config-server:
    restart: always
    image: semanticsearch/minerva.config-server:1.0.0
    hostname: localhost
    ports:
      - 8888:8888

  rabbitmq-service:
    restart: always
    image: semanticsearch/minerva.rabbitmq:1.0.0
    hostname: localhost
    ports:
      - 8095:8095

  image-crawler-service:
    restart: always
    image: semanticsearch/minerva.image-crawler:1.0.0
    hostname: localhost
    ports:
      - 8090:8090

  video-crawler-service:
    restart: always
    image: semanticsearch/minerva.video-crawler:1.0.0
    hostname: localhost
    ports:
      - 8083:8083

  code-crawler-service:
    restart: always
    image: semanticsearch/minerva.code-crawler:1.0.0
    hostname: localhost
    ports:
      - 8080:8080

  content-crawler-service:
    restart: always
    image: semanticsearch/minerva.content-crawler:1.0.0
    hostname: localhost
    ports:
      - 8081:8081

  indexer-service:
    restart: always
    image: semanticsearch/minerva.indexer-service:1.0.0
    hostname: localhost
    ports:
      - 8051:8051

  authentication-service:
    restart: always
    image: semanticsearch/minerva.authentication-service:1.0.0
    hostname: localhost
    ports:
      - 8090:8093

  pos-tagging-service:
    restart: always
    image: semanticsearch/minerva.pos-tagging:1.0.0
    hostname: localhost
    ports:
      - 8087:8087

  confidence-score-service:
    restart: always
    image: semanticsearch/minerva.confidence-score-service:1.0.0
    hostname: localhost
    ports:
      - 8084:8084

  lemmatization-service:
    restart: always
    image: semanticsearch/minerva.lemmatization-service:1.0.0
    hostname: localhost
    ports:
      - 9000:9000

  nlp-service:
    restart: always
    image: semanticsearch/minerva.nlp-service:1.0.0
    hostname: localhost
    ports:
      - 9001:9001

  search-service:
    restart: always
    image: semanticsearch/minerva.search-service:1.0.0
    hostname: localhost
    ports:
      - 8999:8999

  orchestra-service:
    restart: always
    image: semanticsearch/minerva.orchestration:1.0.0
    hostname: localhost
    ports:
      - 8890:8890

  user-search-service:
    restart: always
    image: semanticsearch/minerva.user-search:1.0.0
    hostname: localhost
    ports:
      - 8091:8091

  dialog-manger:
    restart: always
    image: semanticsearch/minerva.dialog-manager:1.0.0
    hostname: localhost
    ports:
      - 8081:8081

  recommendation-service:
    restart: always
    image: semanticsearch/minerva.recommendations:1.0.0
    hostname: localhost
    ports:
      - 8092:8092

  neo4j-manager:
    restart: always
    image: semanticsearch/minerva.neo4j-manger:1.0.0
    hostname: localhost
    ports:
      - 8096:8096

  angular-search-interface:
    restart: always
    image: semanticsearch/minerva.angular-search-interface:1.0.0
    hostname: localhost
    ports:
      - 4200:4200

