version: '2.0'

services:
  image-crawler-service:
    restart: always
    build: ./ImageCrawlerService
    hostname: 172.23.238.178
    ports:
      - 8090:8090

  orchestra-service:
    restart: always
    build: ./OrchestraService
    hostname: 172.23.238.178
    ports:
      - 8890:8890

  user-search-service:
    restart: always
    build: ./UserSearchService
    hostname: 172.23.238.178
    ports:
      - 8091:8091

  recommendation-service:
    restart: always
    build: ./RecommendationService
    hostname: 172.23.238.178
    ports:
      - 8092:8092

  neo4j-manager:
    restart: always
    build: ./Neo4jManager
    hostname: 172.23.238.178
    ports:
      - 8096:8096

  redis:
    image: redis:latest
    restart: always
    hostname: 172.23.238.178
    ports:
      - 6379:6379
    volumes:
      - $HOME/redis/data:/data
